import type { Character } from '../../types';

export function makeCharacter(overrides: Partial<Character> = {}): Character {
  return {
    id: 'hero-1',
    name: 'Valerius',
    class: 'Fighter',
    race: 'Human',
    level: 1,
    hp: { current: 12, max: 12 },
    stats: { str: 15, dex: 10, con: 14, int: 8, wis: 12, cha: 14 },
    inventory: [
      { name: 'Longsword', quantity: 1, type: 'weapon', stats: { damage: '1d8', damageType: 'slashing', properties: ['versatile (1d10)'] }, equipped: true },
      { name: 'Shield', quantity: 1, type: 'shield', stats: { acBonus: 2 }, equipped: true },
      { name: 'Chain Mail', quantity: 1, type: 'armor', stats: { acFormula: '16' }, equipped: true },
    ],
    currency: { gp: 15, sp: 5, cp: 0 },
    location: 'The Rusty Tankard',
    experience: 0,
    experienceToNextLevel: 300,
    unusedStatPoints: 0,
    maxHpBonus: 0,
    hitDice: { current: 1, max: 1 },
    skills: { religion: 1, persuasion: 1 },
    unusedSkillPoints: 2,
    ...overrides,
  };
}

export function makeWizard(overrides: Partial<Character> = {}): Character {
  return {
    id: 'wizard-1',
    name: 'Magus',
    class: 'wizard',
    race: 'elf',
    level: 5,
    hp: { current: 32, max: 32 },
    stats: { str: 8, dex: 14, con: 12, int: 16, wis: 13, cha: 10 },
    inventory: [{ name: 'Spellbook', quantity: 1, type: 'gear' }],
    currency: { gp: 10, sp: 0, cp: 0 },
    location: 'Test Lab',
    experience: 0,
    experienceToNextLevel: 6500,
    unusedStatPoints: 0,
    maxHpBonus: 0,
    hitDice: { current: 5, max: 5 },
    skills: { arcana: 1, history: 1 },
    unusedSkillPoints: 0,
    subclassId: 'school-of-evocation',
    resources: [
      { id: 'spell-slot-1', name: 'Level 1 Spell Slot', current: 4, max: 4, resetOn: 'long', source: 'class', sourceId: 'wizard' },
      { id: 'spell-slot-2', name: 'Level 2 Spell Slot', current: 3, max: 3, resetOn: 'long', source: 'class', sourceId: 'wizard' },
      { id: 'spell-slot-3', name: 'Level 3 Spell Slot', current: 2, max: 2, resetOn: 'long', source: 'class', sourceId: 'wizard' },
    ],
    knownSpells: ['magic-missile', 'shield', 'fireball', 'burning-hands', 'fire-bolt'],
    preparedSpells: ['magic-missile', 'shield', 'fireball', 'burning-hands', 'fire-bolt'],
    racialTraits: ['fey-ancestry', 'trance'],
    concentrationSpellId: undefined,
    ...overrides,
  };
}

export function makeCleric(overrides: Partial<Character> = {}): Character {
  return {
    id: 'cleric-1',
    name: 'Aria',
    class: 'cleric',
    race: 'human',
    level: 3,
    hp: { current: 22, max: 22 },
    stats: { str: 13, dex: 10, con: 14, int: 10, wis: 16, cha: 12 },
    inventory: [],
    currency: { gp: 0, sp: 0, cp: 0 },
    location: 'Test Lab',
    experience: 0,
    experienceToNextLevel: 900,
    unusedStatPoints: 0,
    maxHpBonus: 0,
    hitDice: { current: 3, max: 3 },
    skills: { religion: 1, medicine: 1 },
    unusedSkillPoints: 0,
    subclassId: 'life-domain',
    resources: [
      { id: 'spell-slot-1', name: 'Level 1 Spell Slot', current: 4, max: 4, resetOn: 'long', source: 'class', sourceId: 'cleric' },
      { id: 'spell-slot-2', name: 'Level 2 Spell Slot', current: 2, max: 2, resetOn: 'long', source: 'class', sourceId: 'cleric' },
      { id: 'channel-divinity', name: 'Channel Divinity', current: 1, max: 1, resetOn: 'short', source: 'class', sourceId: 'cleric' },
    ],
    knownSpells: [],
    preparedSpells: ['cure-wounds', 'bless', 'healing-word', 'shield-of-faith'],
    racialTraits: [],
    concentrationSpellId: undefined,
    ...overrides,
  };
}

export function makeBarbarian(overrides: Partial<Character> = {}): Character {
  return {
    id: 'barb-1',
    name: 'Grishnak',
    class: 'barbarian',
    race: 'half-orc',
    level: 5,
    hp: { current: 47, max: 47 },
    stats: { str: 16, dex: 12, con: 16, int: 8, wis: 10, cha: 8 },
    inventory: [],
    currency: { gp: 0, sp: 0, cp: 0 },
    location: 'Test',
    experience: 0,
    experienceToNextLevel: 6500,
    unusedStatPoints: 0,
    maxHpBonus: 0,
    hitDice: { current: 5, max: 5 },
    skills: {},
    unusedSkillPoints: 0,
    subclassId: 'berserker',
    resources: [
      { id: 'rage', name: 'Rage', current: 3, max: 3, resetOn: 'long', source: 'class', sourceId: 'barbarian' },
    ],
    knownSpells: [],
    preparedSpells: [],
    racialTraits: ['relentless-endurance', 'savage-attacks'],
    concentrationSpellId: undefined,
    ...overrides,
  };
}

export function makeDragonborn(overrides: Partial<Character> = {}): Character {
  return {
    id: 'drac-1',
    name: 'Vorel',
    class: 'fighter',
    race: 'dragonborn',
    level: 1,
    hp: { current: 12, max: 12 },
    stats: { str: 15, dex: 10, con: 14, int: 8, wis: 10, cha: 13 },
    inventory: [],
    currency: { gp: 0, sp: 0, cp: 0 },
    location: 'Test',
    experience: 0,
    experienceToNextLevel: 300,
    unusedStatPoints: 0,
    maxHpBonus: 0,
    hitDice: { current: 1, max: 1 },
    skills: {},
    unusedSkillPoints: 0,
    subclassId: 'champion',
    resources: [
      { id: 'breath-weapon', name: 'Breath Weapon', current: 1, max: 1, resetOn: 'short', source: 'race', sourceId: 'dragonborn' },
    ],
    knownSpells: [],
    preparedSpells: [],
    racialTraits: ['draconic-ancestry', 'breath-weapon', 'damage-resistance-dragonborn'],
    concentrationSpellId: undefined,
    draconicAncestry: 'blue',
    draconicDamageType: 'lightning',
    ...overrides,
  };
}

export function makeBard(overrides: Partial<Character> = {}): Character {
  return {
    id: 'bard-1',
    name: 'Lyra',
    class: 'bard',
    race: 'half-elf',
    level: 3,
    hp: { current: 18, max: 18 },
    stats: { str: 8, dex: 14, con: 12, int: 10, wis: 13, cha: 16 },
    inventory: [],
    currency: { gp: 0, sp: 0, cp: 0 },
    location: 'Test',
    experience: 0,
    experienceToNextLevel: 900,
    unusedStatPoints: 0,
    maxHpBonus: 0,
    hitDice: { current: 3, max: 3 },
    skills: { performance: 1, persuasion: 1 },
    unusedSkillPoints: 0,
    subclassId: 'college-of-lore',
    resources: [
      { id: 'spell-slot-1', name: 'Level 1 Spell Slot', current: 4, max: 4, resetOn: 'long', source: 'class', sourceId: 'bard' },
      { id: 'spell-slot-2', name: 'Level 2 Spell Slot', current: 2, max: 2, resetOn: 'long', source: 'class', sourceId: 'bard' },
    ],
    knownSpells: ['vicious-mockery', 'cure-wounds', 'faerie-fire', 'sleep'],
    preparedSpells: [],
    racialTraits: ['fey-ancestry', 'skill-versatility'],
    concentrationSpellId: undefined,
    halfElfStatChoices: ['str', 'dex', 'con'],
    ...overrides,
  };
}

export function makeRogue(overrides: Partial<Character> = {}): Character {
  return {
    id: 'rogue-1',
    name: 'Shadow',
    class: 'rogue',
    race: 'halfling',
    level: 3,
    hp: { current: 20, max: 20 },
    stats: { str: 8, dex: 16, con: 14, int: 12, wis: 10, cha: 12 },
    inventory: [
      { name: 'Rapier', quantity: 1, type: 'weapon', stats: { damage: '1d8', damageType: 'piercing', properties: ['finesse'] }, equipped: true },
      { name: 'Leather Armor', quantity: 1, type: 'armor', stats: { acFormula: '11+dex' }, equipped: true },
      { name: "Thieves' Tools", quantity: 1, type: 'gear' },
    ],
    currency: { gp: 10, sp: 0, cp: 0 },
    location: 'Test',
    experience: 0,
    experienceToNextLevel: 900,
    unusedStatPoints: 0,
    maxHpBonus: 0,
    hitDice: { current: 3, max: 3 },
    skills: { stealth: 1, perception: 1, sleightOfHand: 1 },
    unusedSkillPoints: 0,
    sneakAttackDice: 2,
    resources: [],
    knownSpells: [],
    preparedSpells: [],
    racialTraits: ['lucky', 'brave', 'halfling-nimbleness'],
    concentrationSpellId: undefined,
    ...overrides,
  };
}
